apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cockroachdb
  name: cockroachdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cockroachdb
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: cockroachdb
    spec:
      containers:
      - args:
        - start-single-node
        - --insecure
        image: cockroachdb/cockroach:latest
        name: cockroachdb-todo-app
        ports:
        - containerPort: 8080
          protocol: TCP
      hostname: cockroachdb
      restartPolicy: Always
