apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: todo-app
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-app
  template:
    metadata:
      labels:
        io.kompose.service: todo-app
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgres://root@cockroachdb:26257/defaultdb
        image: todo-app:latest
        imagePullPolicy: IfNotPresent
        name: web-server-todo-app
        ports:
        - containerPort: 8000
          protocol: TCP
      hostname: web-server
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: todo-app
  name: todo-app
spec:
  ports:
    - name: web
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: todo-app
