apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: todo-app
  name: todo-app
spec:
  ports:
    - name: web
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: todo-app
