apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: todo-app
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: todo-app
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgres://root@cockroachdb:26257/defaultdb
        image: localhost/todo-app:latest
        imagePullPolicy: IfNotPresent
        name: web-server-todo-app
        ports:
        - containerPort: 8000
          protocol: TCP
      hostname: web-server
      restartPolicy: Always
