GET http://localhost:8000/api/todos
###
GET http://localhost:8000/api/todos/1027696631890542593
###
POST http://localhost:8000/api/todos
Content-Type: application/json

{
  "description": "test app",
  "done": false
}
###
PUT http://localhost:8000/api/todos
Content-Type: application/json

{
  "id": "123",
  "description": "write app",
  "done": true
}