services:
  golang:
    command: tail -F anything
    container_name: golang-todo-app
    depends_on:
      - cockroachdb
    environment:
      - DATABASE_URL=postgres://root@cockroachdb:26257/defaultdb
    hostname: golang
    image: golang:latest
    ports:
      - "8000:8000"
    volumes:
      - ..:/todo-app
  cockroachdb:
    command: start-single-node --insecure
    container_name: cockroachdb
    hostname: cockroachdb
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
      - "8080:8080"