apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ..\.k8s.cockroachdb.cluster\ -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cockroachinit
  name: cockroachinit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cockroachinit
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ..\.k8s.cockroachdb.cluster\ -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: cockroachinit
    spec:
      containers:
        - command:
            - sh
            - -c
            - sleep 5 && cockroach init --insecure --host=cockroachdb0:26258
          image: cockroachdb/cockroach:latest
          name: cockroachdbinit-todo-app
      hostname: cockroachinit
      restartPolicy: Always
