apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ..\.k8s.cockroachdb.cluster\ -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: todo-app
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ..\.k8s.cockroachdb.cluster\ -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: todo-app
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://root@cockroachdb0:26257/defaultdb
          image: todo-app:latest
          name: web-server-todo-app
          ports:
            - containerPort: 8000
              protocol: TCP
      hostname: web-server
      restartPolicy: Always
