services:
  todo-app:
    build:
      context: ..
      dockerfile: .docker/dockerfile
    container_name: web-server-todo-app
    depends_on:
    - cockroachdb0
    - cockroachdb1
    - cockroachdb2
    environment:
    - DATABASE_URL=postgres://root@cockroachdb0:26257/defaultdb
    hostname: web-server
    image: todo-app:latest
    ports:
    - "8000:8000"
  cockroachdb0:
    command:
      start
      --listen-addr=:26258
      --sql-addr=:26257
      --insecure
      --join=cockroachdb1:26258,cockroachdb2:26258
    container_name: cockroachdb0-todo-app
    hostname: cockroachdb0
    image: cockroachdb/cockroach:latest
    ports:
    - "8080:8080"
  cockroachdb1:
    command:
      start
      --listen-addr=:26258
      --sql-addr=:26257
      --insecure
      --join=cockroachdb0:26258,cockroachdb2:26258
    container_name: cockroachdb1-todo-app
    hostname: cockroachdb1
    image: cockroachdb/cockroach:latest
    ports:
    - "8081:8080"
  cockroachdb2:
    command: 
      start
      --listen-addr=:26258
      --sql-addr=:26257
      --insecure
      --join=cockroachdb0:26258,cockroachdb1:26258
    container_name: cockroachdb2-todo-app
    hostname: cockroachdb2
    image: cockroachdb/cockroach:latest
    ports:
    - "8082:8080"
  cockroachinit:
    container_name: cockroachdbinit-todo-app
    depends_on:
    - cockroachdb0
    - cockroachdb1
    - cockroachdb2
    entrypoint: ["sh", "-c", "sleep 5 && cockroach init --insecure --host=cockroachdb0:26258"]
    hostname: cockroachinit
    image: cockroachdb/cockroach:latest